[package]
name = "op-alloy-rpc-types-engine"
description = "Optimism RPC types for the `engine` namespace"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace
op-alloy-consensus.workspace = true
op-alloy-protocol.workspace = true
op-alloy-genesis.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true

# Encoding
snap = { workspace = true, optional = true }
ethereum_ssz = { workspace = true, optional = true }

# serde
serde = { workspace = true, optional = true }
alloy-serde = { workspace = true, optional = true }

# misc
thiserror.workspace = true
derive_more = { workspace = true, features = ["display"] }
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
arbtest.workspace = true
serde_json.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["arbitrary"] }

[features]
default = ["std", "serde"]
std = [
  "dep:snap",
  "dep:ethereum_ssz",
  "alloy-rpc-types-engine/ssz",
  "alloy-primitives/std",
  "alloy-rpc-types-engine/std",
  "op-alloy-consensus/std",
  "op-alloy-protocol/std",
]
serde = [
  "dep:serde",
  "dep:alloy-serde",
  "op-alloy-protocol/serde",
  "alloy-rpc-types-engine/serde",
]
arbitrary = [
  "std",
  "dep:arbitrary",
  "alloy-primitives/arbitrary",
  "alloy-primitives/rand",
]
