[package]
name = "op-alloy-registry"
description = "Re-export of op-rs/maili-registry"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
maili-registry = { workspace = true, default-features = false }

[features]
default = ["std", "map-foldhash"]
map-hashbrown = ["maili-registry/map-hashbrown"]
map-foldhash = ["maili-registry/map-foldhash"]
std = ["maili-registry/std"]
