[package]
name = "op-alloy-rpc-jsonrpsee"
description = "Optimism RPC Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
authors.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Alloy
op-alloy-rpc-types.workspace = true
op-alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-eips.workspace = true
alloy-primitives.workspace = true

# rpc
jsonrpsee.workspace = true

[features]
default = ["std"]
std = [
    "op-alloy-rpc-types/std",
    "op-alloy-rpc-types-engine/std",
    "alloy-eips/std",
    "alloy-primitives/std",
]
client = [
    "jsonrpsee/client",
    "jsonrpsee/async-client",
]
