name: Book Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    name: Publish to GitHub Pages
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup mdbook
        run: |
          cargo install --version 0.4.40 mdbook
          cargo install mdbook-mermaid mdbook-template mdbook-alerts
      - name: Build book
        working-directory: ./book
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
