name: deps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [cron: "00 00 * * *"]

jobs:
  cargo-deny:
    with:
      rust-toolchain: nightly
    uses: tempoxyz/gh-actions/.github/workflows/rust-deny.yml@b35994a23aaf6acf4d5e2f91d18235a6e2f90e95 # 2026-09-23T08-07-21Z-b35994a2
    permissions:
      contents: read
      id-token: write
