name: deps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [cron: "00 00 * * *"]

jobs:
  cargo-deny:
    name: cargo deny check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@48ff2b0c97ede86c9f10d105424380b9605f790d
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: nightly
      - name: Install cargo-deny
        uses: tempoxyz/gh-actions/vendor/taiki-e/install-action@48ff2b0c97ede86c9f10d105424380b9605f790d
        with:
          tool: cargo-deny@0.20.2
          checksum: true
          fallback: none
      - run: cargo deny --all-features check
