name: deps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [cron: "00 00 * * *"]

jobs:
  cargo-deny:
    uses: tempoxyz/gh-actions/.github/workflows/rust-deny.yml@2da86a50d7565fbabc606b1ab7fed382b9f4829b # 2026-09-29T12-00-49Z-2da86a50
    permissions:
      contents: read
      id-token: write
    with:
      rust-toolchain: nightly
